### PR TITLE
fixed a bug in tide-search speedup

### PR DESCRIPTION
**Pull request by kfattila**
A bug was fixed possibly responsible for breaking down the tide-xcorr and tide-tailor performance tests. This issue was found by Bill on 4th of Feb. In short, this bug created XCorrs of around 21.5 (which is just too high for any XCorr scores). The bug was quite stochastic in nature, and it was difficult to pinpoint it. I'd appreciate it if you at UW could double check the new performance.

### CODE REVIEW

**Comment by bmx8177** [comment]
Attila, did you run the smoke tests and performance tests on this PR?

**Comment by kfattila** [comment]
Yes, I did run the performance tests. How are they on your side? The smoke tests are broken and we are fixing them in a separate issue. But for now I am concerned about the performance tests.

**Comment by bmx8177** [comment]
The performance tests look good on my end. If you will fix the smoke tests in a different PR then we should be good to merge this.


   On Friday, February 11, 2022, 08:48:13 PM PST, Attila -- Kertesz-Farkas ***@***.***> wrote:  
 
 


Yes, I did run the performance tests. How are they on your side? The smoke tests are broken and we are fixing them in a separate issue. But for now I am concerned about the performance tests.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kfattila** [comment]
@wsnoble,could you also please run the performance tests of this pull request to see if tide works in your machines as well? I'd appreciate it!

**Comment by wsnoble** [comment]
Yes, I did this and the results now look good:

https://noble.gs.washington.edu/~wnoble/proj/crux/crux-toolkit/build-fix-bug-in-tide-search-speedup/test/performance-tests/performance.html

**Comment by kfattila** [comment]
Thanks!

**Comment by kfattila** [comment]
We reviewed and updated the smoke tests. From our side, this branch is ready to merge.

**Comment by CharlesEGrant** [comment]
Sorry for the delay in reviewing this pull request. The changes look fine, and everything builds correction on Linux, MacOS, and Windows. However, I'm getting a smoke-test failure on

`cucumber features/tide-search.feature:39`

The known good file for that test is `good_results/tide-5decoys.txt` and that file doesn't seem to have been updated.

**Comment by wsnoble** [comment]
Can we just switch this test to use reversed rather than shuffled decoys? Or is that case already covered by a different test?

**Comment by kfattila** [comment]
One cannot generate 5 decoys per peptide with reverse.

**Comment by CharlesEGrant** [comment]
Yes, I think removing that test is the thing to do. I'll take a look at the current master to see how it is currently passing.

**Comment by kfattila** [comment]
The smoke test about the 5 decoys is suspended temporarily.

**Pull request merged**
