### PR TITLE
modified and unmodified decoy peptides are shuffled the same way. 2. …

### PR DESCRIPTION
**Pull request by kfattila**
…merged aux location to peptide pb.

The decoy peptide generation is altered, thus, many smoke tests need to be updated.

This branch can be used to generate and search tide-index datasets.

I still need to check backward compatibility, so that new tide-search works properly with old tide-index data.

### CODE REVIEW

**Comment by kfattila** [comment]
I also run performance tests, and the new results are identical to the old ones.

**Comment by kfattila** [comment]
Hi, This branch is ready for code review and merge. This branch contains the following fixes:
1. the decoy peptides generation is identical for modified and unmodified target peptides. This is a request from Uri. 
2. the auxiliary locations are merged to peptide protocol buffer. Thus the whole aux location is not stored in the memory. This makes tide-search memory consumption way much less. 
3. Therefore, tide-index has a new format, but I made tide compatible with old tide index data format. In addition, the old tide-search will break down (carp_fatal) with the new tide-index format. 
4. The changes in tide-index format made the code simpler. I removed a bunch of code. 

Bonus: smokes tests updated, they pass in my machine, (they might fail in Bill's servers), performance tests pass.

**Comment by CharlesEGrant** [comment]
Thank  you for cleaning up the dead comments in files like
src/app/tide/active_peptide_queue.cc! There are few spots where there is new commented out dead code:
sp_scorer.h:97
TideSearchApplication.h:128,266
TideSearchApplication.cpp:513,710,1193,1235
TideIndexApplication.cpp:136

It would be good to remove those.

There is a typo at TideIndexApplication.cpp:461 disjunt->disjoint

In several places it looks like you've passed arguments as pointers that could be passed as references: 

Score() in sp_scorer.[h|cpp] 
GetLocationStr() and GetFlankingAAs() in peptide[h|cc]  ActivePeptideQueue() in active_peptide_queue[h|.cc]

Using references is usually safer than pointers. It makes it impossible to end up with an unexpected null pointer for example.  Consider changing these functions to use references rather than pointers as arguments.

It looks like this simplifies the code quite a bit!

**Comment by kfattila** [comment]
Hi @CharlesEGrant ,

I have removed the dead comments, fixed the typo, and changed pointers to references. Only one exception is the pointer argument in the ActivePeptideQueue, because sometimes a NULL pointer must be passed. Please take a look at the changes, and if all looks fine, feel free to merge it to the main branch. 

Note that, I rerun the tests again, and the smoke tests and the performance tests still pass.

**Review by CharlesEGrant — APPROVED** [review]
Thanks! Attila, those changes address everything I suggested. I'll go ahead and merge now.

**Pull request merged**
