### PR TITLE
Changes to near-current version of ProteoWizard

### PR DESCRIPTION
**Pull request by CharlesEGrant**

### CODE REVIEW

**Comment by CharlesEGrant** [comment]
The very latest version of ProteoWizard completely breaks our build. I have a query into Matt Chambers about this. This commit uses a nearly current version of ProteoWizard that is stored on the Noble Lab web server.

For the conflict, use the version above the '====' divider. 

Very few and minor changes to code, mostly to CMakelsits.txt files and patches for dependencies. No need to review the changes in the patches for boost, since they are simply picking up files from the later version of BOOST that aren't included with the copy of BOOST in ProteoWizard.

**Comment by kfattila** [comment]
Hi Charles,

There are three issues:

- 1st issue

CRUX does not compile on Windows with the latest MSFileReader 3.1 SP4 (which was released Feb 21, 2017). The error message:
```error C3506: there is no typelib registered for LIBID '{F0C5F3E3-4F2A-443E-A74D-0AABE3237494}'```

The whole error msg:
```

    cl /c /I"D:\crux-toolkit\ext\build\src\MSToolkit\include" /W3 /WX- /diagnostics:classic /O2 /Ob2 /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D _CRT_SECURE_NO_WARNINGS /D "CMAKE_INTDIR=\"Release\"" /Gm- /EHsc /MD /GS /fp:precise /Zc:wch
  ar_t /Zc:forScope /Zc:inline /GR /Fo"mstoolkitlite.dir\Release\\" /Fd"mstoolkitlite.dir\Release\mstoolkitlite.pdb" /Gd /TP /errorReport:queue "D:\crux-toolkit\ext\build\src\MSToolkit\src\MSToolkit\MSReader.cpp" "D:\crux-toolkit\ext\bu
  ild\src\MSToolkit\src\MSToolkit\mzMLWriter.cpp" "D:\crux-toolkit\ext\build\src\MSToolkit\src\MSToolkit\RAWReader.cpp"
    MSReader.cpp

D:\crux-toolkit\ext\build\src\MSToolkit\include\MSReader.h(33): error C3506: there is no typelib registered for LIBID '{F0C5F3E3-4F2A-443E-A74D-0AABE3237494}' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-tool
kit\ext\MSToolkit.vcxproj]
D:\crux-toolkit\ext\build\src\MSToolkit\include\MSReader.h(33): fatal error C1104: fatal error importing libid: 'F0C5F3E3-4F2A-443E-A74D-0AABE3237494' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-toolkit\ext\
MSToolkit.vcxproj]
    mzMLWriter.cpp
d:\crux-toolkit\ext\build\src\mstoolkit\include\MSReader.h(33): error C3506: there is no typelib registered for LIBID '{F0C5F3E3-4F2A-443E-A74D-0AABE3237494}' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-tool
kit\ext\MSToolkit.vcxproj]
d:\crux-toolkit\ext\build\src\mstoolkit\include\MSReader.h(33): fatal error C1104: fatal error importing libid: 'F0C5F3E3-4F2A-443E-A74D-0AABE3237494' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-toolkit\ext\
MSToolkit.vcxproj]
    RAWReader.cpp
D:\crux-toolkit\ext\build\src\MSToolkit\include\RAWReader.h(30): error C3506: there is no typelib registered for LIBID '{F0C5F3E3-4F2A-443E-A74D-0AABE3237494}' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-too
lkit\ext\MSToolkit.vcxproj]
D:\crux-toolkit\ext\build\src\MSToolkit\include\RAWReader.h(30): fatal error C1104: fatal error importing libid: 'F0C5F3E3-4F2A-443E-A74D-0AABE3237494' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-toolkit\ext
\MSToolkit.vcxproj]
    Generating Code...
  Done Building Project "D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj" (default targets) -- FAILED.
  Done Building Project "D:\crux-toolkit\ext\build\src\MSToolkit\ALL_BUILD.vcxproj" (default targets) -- FAILED.

  Build FAILED.

  "D:\crux-toolkit\ext\build\src\MSToolkit\ALL_BUILD.vcxproj" (default target) (1) ->
  "D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj" (default target) (3) ->
  (ClCompile target) ->
D:\crux-toolkit\ext\build\src\MSToolkit\include\MSReader.h(33): error C3506: there is no typelib registered for LIBID '{F0C5F3E3-4F2A-443E-A74D-0AABE3237494}' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-tool
kit\ext\MSToolkit.vcxproj]
D:\crux-toolkit\ext\build\src\MSToolkit\include\MSReader.h(33): fatal error C1104: fatal error importing libid: 'F0C5F3E3-4F2A-443E-A74D-0AABE3237494' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-toolkit\ext\
MSToolkit.vcxproj]
d:\crux-toolkit\ext\build\src\mstoolkit\include\MSReader.h(33): error C3506: there is no typelib registered for LIBID '{F0C5F3E3-4F2A-443E-A74D-0AABE3237494}' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-tool
kit\ext\MSToolkit.vcxproj]
d:\crux-toolkit\ext\build\src\mstoolkit\include\MSReader.h(33): fatal error C1104: fatal error importing libid: 'F0C5F3E3-4F2A-443E-A74D-0AABE3237494' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-toolkit\ext\
MSToolkit.vcxproj]
D:\crux-toolkit\ext\build\src\MSToolkit\include\RAWReader.h(30): error C3506: there is no typelib registered for LIBID '{F0C5F3E3-4F2A-443E-A74D-0AABE3237494}' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-too
lkit\ext\MSToolkit.vcxproj]
D:\crux-toolkit\ext\build\src\MSToolkit\include\RAWReader.h(30): fatal error C1104: fatal error importing libid: 'F0C5F3E3-4F2A-443E-A74D-0AABE3237494' [D:\crux-toolkit\ext\build\src\MSToolkit\mstoolkitlite.vcxproj] [D:\crux-toolkit\ext
\MSToolkit.vcxproj]

      0 Warning(s)
      6 Error(s)

  Time Elapsed 00:00:01.85
  Generating crux_version_header, crux_version.h
 
```
This error can be fixed by downloading an earlier version, the MSFileReader 3.0 SP3 (released April 30, 2015).

- 2nd issue: 

The command: ```cmake --build . --config Release --target ALL_BUILD ``` builds CRUX successfully, and it does create the crux.exe. This is fine.

- 3rd issue:

The command: ```cmake --build . --config Release --target INSTALL``` fails with the following error message:
'''
-- Up-to-date: C:/Program Files/crux/bin/CLFIO32.dll
  -- Up-to-date: C:/Program Files/crux/bin/CompassXtractMS.dll
  CMake Error at ext/cmake_install.cmake:36 (file):
    file INSTALL cannot find "D:/crux-toolkit/ext/lib/concrt140.dll": No such
    file or directory.
  Call Stack (most recent call first):
    cmake_install.cmake:56 (include)


C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [D:\crux-toolki
t\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1 [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [D:\crux-toolkit\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code 1. [D:\crux-toolkit\INSTALL.vcxproj]
'''

**Comment by chambm** [comment]
Hah, over the last week I just made most of these changes myself, because I was trying to figure out why Crux percolator is failing when I run it in a Windows Docker container. I didn't want to install VS2017, so I updated it to work with 2022 (should be nearly identical to 2019). Which required updating pwiz to the latest version, which led to me (re-)finding out that the libraries target was broken. Then updating everything to Boost 1.76, protobuf 3.19.4 (discovering it won't respect linking with dynamic runtime), mostly decommissioning the 32-bit builds, etc. I have a PR in for pwiz to fix the libraries target and move libsvm to a namespace so it doesn't conflict with percolator's libsvm. I still haven't figured out why it's failing in a container though.

Try this for the pwiz libraries list:
```
      baf2sql_c.lib
      libhdf5.lib
      libhdf5pp.lib
      libpwiz_analysis_chromatogram_processing.lib
      libpwiz_analysis_common.lib
      libpwiz_analysis_demux.lib
      libpwiz_analysis_diaumpire.lib
      libpwiz_analysis_frequency.lib
      libpwiz_analysis_passive_core.lib
      libpwiz_analysis_peakdetect.lib
      libpwiz_analysis_spectrum_processing.lib
      libpwiz_analysis_spectrum_processing_basic.lib
      libpwiz_data_common.lib
      libpwiz_data_identdata.lib
      libpwiz_data_identdata_version.lib
      libpwiz_data_misc.lib
      libpwiz_data_msdata.lib
      libpwiz_data_msdata_core.lib
      libpwiz_data_msdata_examples.lib
      libpwiz_data_msdata_mz5.lib
      libpwiz_data_msdata_version.lib
      libpwiz_data_proteome.lib
      libpwiz_data_proteome_version.lib
      libpwiz_data_vendor_readers.lib
      libpwiz_reader_abi.lib
      libpwiz_reader_abi_t2d.lib
      libpwiz_reader_agilent.lib
      libpwiz_reader_bruker.lib
      libpwiz_reader_shimadzu.lib
      libpwiz_reader_thermo.lib
      libpwiz_reader_uimf.lib
      libpwiz_reader_unifi.lib
      libpwiz_reader_waters.lib
      libpwiz_tools_common.lib
      libpwiz_utility_chemistry.lib
      libpwiz_utility_math.lib
      libpwiz_utility_minimxml.lib
      libpwiz_utility_misc.lib
      libpwiz_vendor_api_agilent.lib
      libpwiz_vendor_api_bruker.lib
      libpwiz_vendor_api_shimadzu.lib
      libpwiz_vendor_api_thermo.lib
      libpwiz_vendor_api_uimf.lib
      libpwiz_vendor_api_unifi.lib
      libpwiz_version.lib
      libSHA1
      libsqlite3.lib
      libsqlite3pp.lib
      libsvm
      libzlib
      timsdata
```
I removed some extraneous libs you don't need.

I think anywhere you hardcode vc142 you should factor it out into a CMAKE variable. Actually the ideal would be to use `CMAKE_GENERATOR_TOOLSET` because it would have value like `v142` for 2019, but that would need to be tweaked a bit so that it's `vc142` instead. So if you know the CMAKE-fu for that, I suggest that so you can work with multiple VS versions.

Just delete these:
```
    debug libfreetype-vc141-mt-gd-2_4
    optimized libgd-vc141-mt-2_1
    debug libgd-vc141-mt-gd-2_1
    libpng
```

Update the pwiz DLLs to these:
```
    ${CMAKE_CURRENT_BINARY_DIR}/lib/agtsampleinforw.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/baf2sql_c.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BaseCommon.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BaseDataAccess.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BaseError.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BaseTof.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.BCO.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.BCO.Interfaces.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CCO.Calibration.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CCO.Interfaces.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CCO.TemperatureCompensation.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CCO.Transformation.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CCO.Utilities.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CXt.Lc.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CXt.Lc.Factory.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CXt.Lc.Interfaces.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/BDal.CXt.Lc.UntU2.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/CLFIO32.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/CompassXtractMS.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/CRHAKEI2.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/DataReader.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/DualProbeInterfaceParametersCS.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/Google.Protobuf.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/HSReadWrite.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/IdentityModel.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/Interop.EDAL.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/Interop.HSREADWRITELib.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/IOModuleQTFL.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/MassCalcWrapObject.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/MassSpecDataReader.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/mfc90.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/MIDAC.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/mkl_sequential.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/MSMSDBCntl.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcm90.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcp110.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcp120.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcp140.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcp90.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcr110.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcr120.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/msvcr90.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/Newtonsoft.Json.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/ParallelExtensionsExtras.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/PeakItgLSS.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/QTFLDebugLog.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/QTFLProtoCS.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/Shimadzu.LabSolutions.IO.IoModule.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/System.Data.SQLite.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/System.Runtime.Caching.Generic.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/timsdata.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/ucrtbase.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/UIMFLibrary.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/unifi-protobuf-net.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/vcomp110.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/vcomp140.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/vcomp90.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/vcruntime140.dll
    ${CMAKE_CURRENT_BINARY_DIR}/lib/vcruntime140_1.dll
```
I deleted the CLI bindings you don't need that only bloat the download. **Is it possible to just GLOB these out of the lib directory like *.dll?**

Instead of having ASIO checked in to the repo, you could download pwiz's trimmed boost tarball: it's the full set of boost headers and library code, but trimmed of tests and documentation which is the bulk of the size in the official download. (As you've found, the pwiz source tarball does filter out the boost headers to only the ones pwiz uses using the bcp tool).

Also, you could download `pwiz-src-without-t` instead of `pwiz-src`. That'll save you 35mb.

**Comment by CharlesEGrant** [comment]
Thanks Attila, I've fixed each of the issues you've found. Matt, thanks for your input. I'll be implementing those in a separate commit to follow shortly.

**Pull request merged**
