### PR TITLE
Percfilename

### PR DESCRIPTION
**Pull request by wsnoble**
Add a 'filename' column to the Percolator output.  Also fix the txt-format.html file, addressing issue #628 .

### CODE REVIEW

**Comment by bmx8177** [comment]
Do you want to add the 'filename' column to txt-format.html? It is currently missing. 
Also, the columns for the Percolator protein file do not match up with txt-format page.
The columns I see from Percolator output are: ProteinId. ProteinGroupId. q-value, posterior_error_prob, peptideIds

**Comment by wsnoble** [comment]
Oops!  Those were sort of obvious things to miss. Can you look at the updated version of txt-format.html now?

**Comment by bmx8177** [comment]
It still doesn't look right to me. Are we running Percolator the same way? I have attached a screen shot of the current html page. as well as the Percolator log and output.

[percolator.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10714712/percolator.log.txt)
[percolator.target.proteins.txt](https://github.com/crux-toolkit/crux-toolkit/files/10714687/percolator.target.proteins.txt)
image

**Comment by bmx8177** [comment]
For example, I don't see a "peptide-scan.charge" column in my output. But I do see a peptidesIds column.

In addition I see a proteinID column. Note that this is technically different from the proteinIDs column.

**Comment by wsnoble** [comment]
Thanks, Andy. Can you take a look now? I am not sure, in the case of a protein group, how it decides which protein ID goes in the proteinId column.  But I figured I'd just leave that unspecified.

**Comment by bmx8177** [comment]
Ok, everything looks good to me. You can merge now.

**Pull request merged**
