### PR TITLE
Update FAQ

### PR DESCRIPTION
**Pull request by wsnoble**
Added an FAQ entry to explain how to run aTDC.  Made a few other changes to the FAQ as well.

### CODE REVIEW

**Comment by kfattila** [comment]
I think, we explicitly should state that three (3!) things are needed to be specified precisely to run aTDC: 
1. --num-decoys-per-target > 1     (in tide-index)
2. --allow-dups T                            (in tide-index)
3. --concat F                                   (in tide-search)

**Comment by wsnoble** [comment]
Good point. I updated the text to reflect your suggestion.

**Comment by kfattila** [comment]
Hi Bill, 

Sorry, I have just realized that actually there is a 4th conditions to run aTDC. The ```--decoy-format shuffle``` must be shuffle, otherwise peptide-reverse would generate the very same decoy peptides.

**Comment by wsnoble** [comment]
Good point. Can you check it now?

**Comment by kfattila** [comment]
Looks good!

**Comment by kfattila** [comment]
Please delete the aTDC branch.

**Pull request merged**
