### PR TITLE
Tailor

### PR DESCRIPTION
**Pull request by kfattila**
Added Tailor method, updated performance and smoke-tests, and release notes.
--
Attila Kertesz-Farkas

### CODE REVIEW

**Comment by kfattila** [comment]
> Don't we need to update the expected results for the performance test graph? These would be in test/performance-tests/stored-plots/

Those plots in stored-plots/ are updated and they are part of the pull-request. Can you please check again?

**Comment by wsnoble** [comment]
Ah yes, you are right. I can see them now.

**Comment by CharlesEGrant** [comment]
Hi Attila,

Sorry to be so late getting back to you!

> On Jul 25, 2019, at 2:07 AM, Attila Kertesz-Farkas <kfattila@yandex.com> wrote:
> 
> In the file src/app/tide/active_peptide_queue.cc, in the function ActivePeptideQueue::SetActiveRange(), a couple of ‘if’ blocks have clauses added to them. At line 109 in the current version the line
> 
>         if (queue_.empty() || queue_.back()->Mass() <= max_range) {
> 
> is changed to line 114:
> 
>         if (queue_.empty() || queue_.back()->Mass() <= max_range || queue_.size() < min_candidates) {
> 
> 
> If Tailor scoring is not turned on, min_candidates will be 0, so the last Boolean clause will always evaluate to False. It’s in an OR operation, so the overall value of the conditional will remain unchanged from our current code if Tailor scoring is not turned on.
> 
> Can we agree on that this modification is OK?
> 

Yes, completely ok.

 

> On the other hand, line 123 in the same function is currently
> 
>         if (peptide->Mass() > max_range) {
> 
> and becomes line 129
> 
>          if (peptide->Mass() > max_range && queue_.size() > min_candidates) {
> 
> If Tailor scoring is not turned on, min_candidates will be 0, but queue_.size() >= 0. So, depending on the size of the queue, the last Boolean clause could be True or False. It’s part of an AND operation, so the overall sense of the conditional could change from our current code, even if Tailor scoring is not turned on.
> 
> Not exactly, because at this point the queue_.size() cannot be zero.
> If you take a look at the surrounding lines of code:
>  
> 125:      Peptide* peptide = new(&fifo_alloc_peptides_)
> 126:        Peptide(current_pb_peptide_, proteins_, &fifo_alloc_peptides_);
> 127:      queue_.push_back(peptide);
> 128:      //Modified for tailor score calibration method by AKF
> 129:      if (peptide->Mass() > max_range && queue_.size() > min_candidates) {
> 130:        break;
> 131:     }
>  
> Here, you can see there is a queue_.push_back(peptide) before the if statement. So, to the best of my programming knowledge the queue in line 129 cannot be empty.
>  
> Do you agree with me on this issue? Alternatively,  I can change the condition to: "queue_.size() >= min_candidates".
>  

Duoh! Sorry, you are completely correct here. This code is fine.


> Now, allow me to discuss other coding options I considered during Tailor implementation.
> I could leave the iter_ intact as it was before, but then it would require some other ugly code to add more peptides from the reader. I tried this and the code become more complicated IMO.
>  
> Other option is to use an 'if' as follows at code line 145:
>   if (!Params::GetBool("use-tailor-calibration")){
>    while (iter_ != queue_.end() && (*iter_)->Mass() < min_mass->front()) {      //  <-- This is the original code
>      ++iter_;
>    }
>    end_ = iter_;
>  } else {
>   //Added for tailor score calibration method by AKF
>     end_ = queue_.begin();
>     while (end_!= queue_.end() && (*end_)->Mass() < min_mass->front()) {     //   <-- This is the code needed for Tailor.
>       candidatePeptideStatus->push_back(false);  //Added by AKF
>       ++end_;   //Added by AKF
>      }
>   }
> In this case the iter_ would remain the same if Tailor is not used. This is still more doable, but notice that the conditions in the while loop are the same. In my opinion, this would make the code more redundant and a slightly harder to maintain.
>  
> I also note that, the my code in pull-request did pass the smoke and performance tests.  
> 

While that’s a good sign, our smoke test code coverage is by no means 100%. For example, I don’t think we have a smoke test that exercises peptide centric search, and there is a block of code (TideSearchApplication.cpp:615) that explicitly uses the iter_ member from ActivePeptideQueue when peptide centric search is enabled. It really looks to me like it’s expected that iter_ will point to the first peptide in the current mass window (or the end of the active peptide queue) after SetActiveRange() is called. I don’t know that ignoring iter_ will cause problems, but it makes me nervous. 

Could we do this?

```
 iter_ = queue_.begin();
 if (!Params::GetBool("use-tailor-calibration")){
 while (iter_ != queue_.end() && (*iter_)->Mass() < min_mass->front()) {      //  <-- This is the original code
   ++iter_;
   if (Params::GetBool("use-tailor-calibration")){
     candidatePeptideStatus->push_back(false);  //Added by AKF
   }
 }
 end_ = iter_;

```

**Comment by CharlesEGrant** [comment]
> On Jul 26, 2019, at 1:41 AM, William Stafford Noble <wnoble@uw.edu> wrote:
> 
> Charles,
> Were you able to run the performance tests as well?
> 

Yes, you can see the results [here](https://noble.gs.washington.edu/~cegrant/performance-tests/performance.html).

When I ran the smoke tests, 5 tests failed. They were
tide-deiso-pval
tide-isoerrpval
tide-exact-pval-1thread
tide-resEv-pval-1thread
tide-resEv-pval-7thread

The first three failed due to the floating point round difference that Attila warned about. I think the last two failed because Andy fixed a bug and updated the known good files for a couple of tests since Attila made the pull request. We can take care of those when we merge the pull request.

**Comment by kfattila** [comment]
> 
> While that’s a good sign, our smoke test code coverage is by no means 100%. For example, I don’t think we have a smoke test that exercises peptide centric search, and there is a block of code (TideSearchApplication.cpp:615) that explicitly uses the iter_ member from ActivePeptideQueue when peptide centric search is enabled. It really looks to me like it’s expected that iter_ will point to the first peptide in the current mass window (or the end of the active peptide queue) after SetActiveRange() is called. I don’t know that ignoring iter_ will cause problems, but it makes me nervous.
> 
> Could we do this?
> 
> ```
>  iter_ = queue_.begin();
>  if (!Params::GetBool("use-tailor-calibration")){
>  while (iter_ != queue_.end() && (*iter_)->Mass() < min_mass->front()) {      //  <-- This is the original code
>    ++iter_;
>    if (Params::GetBool("use-tailor-calibration")){
>      candidatePeptideStatus->push_back(false);  //Added by AKF
>    }
>  }
>  end_ = iter_;
> ```

Hi Charles,

Thanks for your reply. The code you recommended above is not correct Maybe a '}' is missing. Anyway, I rewrote this code block, and I think the new solution is even more elegant. Please take a look at it in the new pull request.

**Pull request closed without merging**
